update_frequency: 1000
max_steps: 30000
max_epochs: -1
curriculum_type: linear
curriculum_features:
  min_train_size:
    min: 0.85
    max: 0.4
    delay_count: 20000
  scm_num_layers:
    distribution: meta_trunc_norm_log_scaled
    min_max_mean: 0.1
    max_max_mean: 0.3
    min_min_mean: 0.1
    max_min_mean: 0.1
    min_lower_bound: 2
    max_lower_bound: 5
  scm_num_causes:
    distribution: meta_trunc_norm_log_scaled
    min_max_mean: 1
    max_max_mean: 11
    min_min_mean: 1
    max_min_mean: 4
    min_lower_bound: 1
    max_lower_bound: 5
  scm_hidden_dim:
    distribution: meta_trunc_norm_log_scaled
    min_max_mean: 0.1
    max_max_mean: 0.3
    min_min_mean: 0.1
    max_min_mean: 0.1
    min_lower_bound: 10
    max_lower_bound: 50
  scm_noise_std:
    distribution: meta_trunc_norm_log_scaled
    min_max_mean: 0.1
    max_max_mean: 0.4
    min_min_mean: 0.0001
    max_min_mean: 0.0001
    min_lower_bound: 0.0
    max_lower_bound: 0.0