layer_0:
    num_nodes: 10
    next_nodes: 10
    activation: sine
    edges: [[1, 0], [2, 0],
            [0, 1], [9, 1],
            [0, 2], [1, 2],
            [1, 3], [2, 3],
            [2, 4], [3, 4],
            [4, 5],
            [4, 6], [5, 6],
            [5, 7], [6, 7],
            [6, 8], [7, 8],
            [7, 9], [8, 9]]
    weights: []


layer_1:
    num_nodes: 10
    next_nodes: 10
    activation: sqrt_abs
    edges: [[0, 0], [5, 0],
            [3, 1], [2, 1],
            [5, 2], [7, 2],
            [2, 3], [4, 3],
            [4, 4], [6, 4],
            [6, 5],
            [8, 6], [7, 6],
            [7, 7], [9, 7],
            [9, 8], [3, 8],
            [1, 9], [1, 9]]
    weights: []



