device: "cuda"
task: "forecast"
trainer: "foundation_model"
save_key: "val_nmae" #"val_loss"

# history_length = time_series_length - forecast_length
dataset_config:
  dataloader_name: OTFSyntheticDataloader # V3ShardedDataloader
  dataset_name: synthetic_tabular_small # haver4M_synthefy250K
  v3_data_paths: ["/workspace/fmv3_datasets/chronos_1M/fmv3_chronos_all/pretrain/"]
  prior_config_path: "src/synthefy_pkg/prior/config/synthetic_configs/config_small_series.yaml"
  num_channels: 1
  time_series_length: 768 # 768
  forecast_length: 128
  metadata_length: 3460
  timestamp_start_idx: 3
  timestamp_end_idx: 2819
  dataset_description_start_idx: 2819
  dataset_description_end_idx: 3203
  continuous_start_idx: 3203
  continuous_end_idx: 3459
  dataset_idx_start_idx: 3459
  dataset_idx_end_idx: 3460
  text_embedding_dim: 384
  batch_size: 2
  accumulate_grad_batches: 128
  num_timestamp_features: 11
  num_correlates: 46
  num_datasets: 10000
  use_relation_shards: false
  using_synthetic_data: true
  num_workers: 16
  is_regression: true
  is_tabular: false
  curriculum_config_path: "src/synthefy_pkg/prior/config/curriculum_configs/config_assign_prior_curr.yaml"
  mixed_real_synthetic_sampling: false
  run_val_with_eval_bench: true
  eval_bench_data_path: "/workspace/data/synthetic_data/icl_test_medium_always_lag"
  num_eval_bench_batches: 64

# 170752
foundation_model_config:
  model_name: "multilayer_tabicl" #"tabicl" # "synthefy_foundation_forecasting_model_v3e"
  # model_name: "tabicl" #"tabicl" # "synthefy_foundation_forecasting_model_v3e"
  decoder_checkpoint_name: ""
  decoder_input_patch_len: 32
  decoder_output_patch_len: 128
  decoder_num_layers: 10
  decoder_model_dims: 512
  decoder_num_heads: 16
  use_metadata: true
  finetune_timesfm_from_beginning: false
  finetune_timesfm_after_epochs: 100
  timeseries_token_dims: 9
  random_vector_instead_text: false
  mask_timestamp: false
  position_embedding: none
  train_epoch_length: 100
  val_epoch_length: 10
  test_epoch_length: 10
  generate_point_forecast: false
  generate_probabilistic_forecast_using_bins: true
  absolute_max_bar_value: 20 # 50
  num_bins: 5000 # 1000
  bound_output_scale: 0.0
  masking_schemes:
  - "random"
  - "block"
  - "row"
  - "train_test_block"
  block_target_mask_range: 20
  block_target_mask_mean: 300
  block_mask_num: 10
  block_mask_every: false
  row_mask_ratio: 0.1
  row_use_lengths: true
  row_mask_min: 5
  attention_masking_scheme: "interpolation"

metadata_encoder_config:
  channels: ${foundation_model_config.decoder_model_dims}
  n_heads: 8
  num_encoder_layers: 6
  patch_len: ${foundation_model_config.decoder_input_patch_len}
  stride: ${foundation_model_config.decoder_input_patch_len}

execution_config:
  save_path: training_logs
  experiment_name: "plusplus_with_expert_and_curriculum"
  run_name: "no_expert_curriculum_evalbench_tabular_synthetic"
  generation_save_path: generation_logs
  use_mlflow: true
  mlflow_tracking_uri: "http://10.15.33.49:5000" # H100 - 4

training_config:
  target_mask_ratio: 0.1
  patience: 50
  learning_rate: 1e-4
  n_plots: 4
  auto_lr_find: True
  log_every_n_steps: 1
  check_test_every_n_epoch: 5000
  num_devices: 1
  check_val_every_n_epoch: 1
  strategy: "ddp_find_unused_parameters_true"
  save_all_checkpoints: true
  save_checkpoint_every_n_epochs: 2
  model_name: "foundation_model"
  model_file: "fmv3"
  num_ar_batches: 0
  precision: "16-mixed"
  gradient_clipping: 1.0
  max_epochs: 20
  pred_plot_freq: 1000
  # lr_scheduler:
  #     scheduler_name: "cosine_warmup"
  #     warmup_proportion: 0.001
  #     max_steps: 20000

prior_config:
  max_classes: 10
  dataset_length: 1024
  # override_activations: "identity"

tabicl_config:
  embed_dim: 512 # 512
  col_num_blocks: 3 # 3 # 8
  col_nhead: 8 # 4 # 16
  col_num_inds: 128 # 512

  row_num_blocks: 3 # 3 # 8
  row_nhead: 8 # 16
  row_num_cls: 4 # 4
  row_rope_base: 10000

  # icl_num_blocks: 12
  # icl_nhead: 4

  random_train_mask_ratio: 0.2
  num_layers: 5
  # weight_range: [-0.5, 0.5]
  preserve_col_order: true
  use_full_reg: true
  use_time_mask: true
  train_as_univariate_forecast: true
  external_column_embedder: "sfm_v3e"

token_decoder_config:
  decoder_type: "linear"
  token_forecast_length: 1
  output_dim: 128
  model_dim: 128
  num_layers: 1
