device: "cuda"
task: "forecast"

# {'time_series_length': 48, 'num_channels': 5, 'num_discrete_conditions': 36, 'num_continuous_labels': 34, 'num_timestamp_labels': 3}
dataset_config:
  dataset_name: opanga2
  num_channels: 5
  time_series_length: 48
  num_continuous_labels: 34
  discrete_condition_embedding_dim: 64
  latent_dim: 64

  num_timestamp_labels: 3
  use_metadata: True
  use_timestamp: True
  batch_size: 256
  forecast_length: 16

  num_discrete_labels: 2
  num_discrete_conditions: 36

denoiser_config:
  denoiser_name: "synthefy_forecasting_model_v2"
  d_model: 256
  patch_len: 16
  stride: 8
  dropout: 0.1
  e_layers: 6
  d_layers: 1
  d_ff: 512
  n_heads: 8
  activation: "gelu"
  factor: 3
  output_attention: True
  use_metadata: True
  ratio: 0.5

metadata_encoder_config:
  use_sa_layer: True
  channels: ${denoiser_config.d_model}
  n_heads: 8
  num_encoder_layers: 2

execution_config:
  save_path: training_logs
  run_name: "synthefy_forecasting_model_v2_opanga2"
  generation_save_path: generation_logs
  experiment_name: Time_Series_Diffusion_Training

training_config:
  max_epochs: 100
  learning_rate: 1e-4
  n_plots: 4
  save_after_every_iters: 5
  save_after_every_n_epochs: 5
  auto_lr_find: True
  check_val_every_n_epoch: 5
  log_every_n_steps: 100
  num_devices: 1
  strategy: "auto"
