device: "cuda"
task: "synthesis"

dataset_config:
  dataset_name: se_UC1device
  time_series_length: 256
  required_time_series_length: 256
  num_channels: 9
  num_discrete_conditions: 4
  num_discrete_labels: 1
  num_continuous_labels: 11
  num_timestamp_labels: 0
  use_timestamp: False
  latent_dim: 128
  discrete_condition_embedding_dim: 128
  batch_size: 16

 
denoiser_config:
  positional_embedding_dim: 128
  channel_embedding_dim: 16
  channels: 256
  n_heads: 8
  n_layers: 10
  dropout_pos_enc: 0.2 
  use_metadata: True
  use_periodic_projection: True

metadata_encoder_config:
  channels: 256
  n_heads: 8
  num_encoder_layers: 2

execution_config:
  save_path: training_logs
  run_name: channel_256_layers_10
  generation_save_path: generation_logs
  experiment_name: Time_Series_Diffusion_Training

training_config:
  max_epochs: 5000
  n_plots: 10
  auto_lr_find: True
  check_val_every_n_epoch: 5
  check_test_every_n_epoch: 5
  log_every_n_steps: 1
  num_devices: 1
  strategy: "auto"