device: cuda
task: synthesis
dataset_config:
  dataset_name: child_sleep_states
  num_channels: 2
  forecast_length: 128
  time_series_length: 256
  required_time_series_length: 256
  num_discrete_conditions: 3
  num_continuous_labels: 2
  num_discrete_labels: 1
  discrete_condition_embedding_dim: 64
  latent_dim: 64
  batch_size: 16
  num_workers: 32
  use_metadata: true
  num_timestamp_labels: 0
denoiser_config:
  positional_embedding_dim: 128
  channel_embedding_dim: 16
  channels: 256
  n_heads: 8
  n_layers: 8
  dropout_pos_enc: 0.2
  use_metadata: true
  use_periodic_projection: true
metadata_encoder_config:
  channels: 256
  n_heads: 8
  num_encoder_layers: 2
execution_config:
  save_path: training_logs
  run_name: synthesis_child_sleep_states
  generation_save_path: generation_logs
  experiment_name: Time_Series_Diffusion_Training
training_config:
  max_epochs: 500
  learning_rate: 0.0001
  n_plots: 4
  auto_lr_find: true
  check_val_every_n_epoch: 5
  check_test_every_n_epoch: 5
  log_every_n_steps: 1
  num_devices: 8
  strategy: auto
