device: "cuda"
task: "synthesis"

dataset_config:
  dataset_name: twamp_one_month
  num_channels: 5
  time_series_length: 96
  required_time_series_length: 96
  num_discrete_conditions: 310
  num_discrete_labels: 8
  num_continuous_labels: 20
  discrete_condition_embedding_dim: 128
  latent_dim: 64
  batch_size: 16

  # Constraints related
  use_constraints: False
  extract_equality_constraints_from_windows: False
  projection_during_synthesis: clipping
  # projection_during_synthesis: strict
  constraints: ["min", "max"]
  # constraints: ["argmax", "max and argmax", "argmin", "min and argmin"]

denoiser_config:
  positional_embedding_dim: 128
  channel_embedding_dim: 16
  channels: 256
  n_heads: 8
  n_layers: 6
  dropout_pos_enc: 0.2 
  use_metadata: True

metadata_encoder_config:
  channels: 256
  n_heads: 8
  num_encoder_layers: 2

execution_config:
  save_path: training_logs
  run_name: march_20_2024
  generation_save_path: generation_logs
  experiment_name: Time_Series_Diffusion_Training

training_config:
  max_epochs: 500
  n_plots: 10
  auto_lr_find: True
  check_val_every_n_epoch: 10
  check_test_every_n_epoch: 10
  log_every_n_steps: 1
  num_devices: 1
