device: "cuda"
task: "synthesis"

dataset_config:
  dataset_name: ppg_samsung
  time_series_length: 512
  required_time_series_length: 512
  num_channels: 5
  num_discrete_conditions: 19
  num_discrete_labels: 1
  num_continuous_labels: 18
  num_timestamp_labels: 0
  use_timestamp: False
  latent_dim: 64
  discrete_condition_embedding_dim: 64
  batch_size: 64
  num_workers: 32
denoiser_config:
  denoiser_name: "diffusion_transformer"
  positional_embedding_dim: 128
  channel_embedding_dim: 16
  channels: 256
  n_heads: 8
  n_layers: 12
  dropout_pos_enc: 0.2
  use_metadata: true
  use_periodic_projection: true
  patch_len: 32
  stride: 32
  metadata_embedding_dim: 32

metadata_encoder_config:
  channels: 256
  n_heads: 8
  num_encoder_layers: 2

execution_config:
  save_path: training_logs
  run_name: synthesis_ppg_samsung_stride_32
  generation_save_path: generation_logs
  experiment_name: Time_Series_Diffusion_Training
  inference_seed: 10

training_config:
  max_epochs: 1000
  n_plots: 10
  auto_lr_find: True
  check_val_every_n_epoch: 3
  check_test_every_n_epoch: 3
  log_every_n_steps: 1
  num_devices: 2
  strategy: "ddp_find_unused_parameters_true"
